exchangealgo/accounts/urls.py
from django.urls import path, include
from .import views

urlpatterns = [
    path('registration/', views.registration_view, name='registration_view'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('user/<str:username>/', views.user_profile, name='user_profile'),
    path("user/<str:username>/social/", views.user_profile_view, name="user_profile_social"),
    path('list_user/', views.UserListViewCBV.as_view(), name="list_user"),
    path("users/", views.UserList.as_view(), name="users_list_social"),

]

exchangealgo/exchangealgo/urls.py
from django.contrib import admin
from django.urls import path, include
from coinmarketalgo.views import buyalgomkt, HomePrincipalView
from ordertransaction.views import placeOrders, activeOrders, gain_loss, order_status_book_view,\
    transaction_user, ListOrder, deleteOrder
from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('buycoin/', buyalgomkt, name='purchase'),
    path('buy_sell_dex/', placeOrders, name='match_orders'),
    path('activeOrders/', activeOrders, name='activeOrders'),
    path('gain_loss/', gain_loss, name='gain_loss'),
    path('orderbook/', order_status_book_view, name='orderbook'),
    path('trasaction_jeson/', transaction_user, name='trasaction_jeson'),
    path('forum/', include('forum.urls')),
    path('', HomePrincipalView, name='homepage'),
    path('status/', ListOrder.as_view(), name='status'),
    path('status/<int:n>/remove', deleteOrder, name="delete_orders")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exchangealgo/forum/urls.py
from django.urls import path
from . import views
from accounts.views import SocialPage

urlpatterns = [
    path("new-section/", views.CreateSection.as_view(), name="create_section"),
    path("section/<int:pk>/", views.section_view, name="section_view"),
    path("section/<int:pk>/crea-discussione/", views.create_discussion, name="create_discussion"),
    path("discussion/<int:pk>/", views.discussion_view, name="discussion_view"),
    path("discussion/<int:pk>/ansewer/", views.add_request, name="request_discussion"),
    path("discussion/<int:id>/delete_post/<int:pk>/", views.DeletePost.as_view(), name="delete_post"),
    path("socialpage", SocialPage.as_view(), name="social_page"),
]

exchangealgo/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from djongo.models.fields import ObjectIdField
from .coinmarketcap import algoValue
import random


class Profile(models.Model):
    _id = ObjectIdField()
    user = models.ForeignKey(User, on_delete=models.CASCADE,  related_name='profile')
    ips = models.Field(default=[])
    subprofiles = models.Field(default={})
    n = random.randint(1, 10)
    ALGO_Wallet = models.FloatField(default=n)
    USD_wallet = models.FloatField(default=1000)
    profit = models.FloatField(default=0)
    ALGO_Pending_Wallet = models.FloatField(default=0)
    USD_Pending_Wallet = models.FloatField(default=0)

    class Meta:
        ordering = ['profile']

    def __str__(self):
        return "profile for user {}".format(self.user.username)

exchangealgo/forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import math


class HomepageSection(models.Model):
    title_section = models.CharField(max_length=80)
    description = models.CharField(max_length=150, blank=True, null=True)
    logo_section = models.ImageField(blank=True, null=True)

    class Meta:
        verbose_name = "Section"
        verbose_name_plural = "Sections"

    def __str__(self):
        return self.title_section

    def get_absolute_url(self):
        return reverse("section_view", kwargs={"pk": self.pk})

    def get_last_discussions(self):

        return Discussion.objects.filter(membership=self).order_by("-published")[:2]

    def get_number_of_posts_in_section(self):

        return Post.objects.filter(discussion__membership=self).count()


class Discussion(models.Model):
    title = models.CharField(max_length=120)
    published = models.DateTimeField(auto_now_add=True)
    author_discussion = models.ForeignKey(User, on_delete=models.CASCADE, related_name="discussions")
    membership = models.ForeignKey(HomepageSection, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Discussion"
        verbose_name_plural = "Discussions"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("discussion_view", kwargs={"pk": self.pk})

    def get_n_pages(self):
        posts_discussion = self.post_set.count()
        n_page = math.ceil(posts_discussion / 5)
        return n_page


class Post(models.Model):
    author_post = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    content = models.TextField()
    published = models.DateTimeField(auto_now_add=True)
    discussion = models.ForeignKey(Discussion, on_delete=models.CASCADE)

    def __str__(self):
        return self.author_post.username

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        return self.author_post.username

exchangealgo/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    email = forms.CharField(max_length=50, required=True, widget=forms.EmailInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']



class UserEditForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('username',  'email', 'password',)

exchangealgo/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from .forms import RegistrationForm, UserEditForm
from .models import Profile
from .coinmarketcap import algoValue, algo_perc24h, algo_vol24h, algo_marketCap
from django.contrib import messages
from coinmarketalgo.models import Purchase
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from forum.models import Discussion, Post, HomepageSection
from django.db.models import Q
from ordertransaction.models import Transaction, Order


def registration_view(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password1"]
            User.objects.create_user(username=username, password=password, email=email)
            user = authenticate(username=username, password=password)
            Profile.objects.create(user=user)
            profile = Profile.objects.get(user=user)
            login(request, user)
            messages.success(request,
                             f'Your Account has been created successfully, you have received {profile.ALGO_Wallet} '
                             f'ALGO '
                             f'and {profile.USD_wallet}$  for registering. See in your wallet!')
            return redirect("social_page")
    else:
        form = RegistrationForm()
    context = {"form": form}
    return render(request, "accounts/registration.html", context)


def user_profile(request, username):
    user = get_object_or_404(User, username=username)
    profile = Profile.objects.get(user=user)
    algowallet = profile.ALGO_Wallet
    pending_ALGO = profile.ALGO_Pending_Wallet
    pending_USD = profile.USD_Pending_Wallet
    print(profile.USD_Pending_Wallet)
    price = algoValue()
    market_cap = algo_marketCap()
    vol24h = algo_perc24h()
    percent_24h = algo_vol24h()
    orders = Order.objects.filter(profile=profile).order_by('datetime')
    orders_transactions = Transaction.objects.filter(Q(call=request.user) | Q(put=request.user)).order_by('-datetime')
    purchase = Purchase.objects.filter(profile=profile)
    algo_usd = round(profile.ALGO_Wallet * algoValue(), 3)
    remaining_balance = round(profile.USD_wallet, 6)
    profit = round(profile.profit)
    context = {'user': user, 'algo_usd': algo_usd, 'remaining_balance': remaining_balance, 'purchase': purchase,
               'profit': profit, 'price': price, 'market_cap': market_cap, 'vol24h': vol24h, 'percent_24h': percent_24h,
               'orders_transactions': orders_transactions, 'orders': orders,
               'algowallet': algowallet, 'pending_USD':  pending_USD, 'pending_ALGO': pending_ALGO}
    return render(request, 'accounts/user_profile.html', context)


def edit_profile(request):
    if request.method == 'POST':
        userform = UserEditForm(data=request.POST, instance=request.user)
        if userform.is_valid():
            userform.save()
            messages.success(request, ('You just edited your profile'))
            return redirect('/')
        else:
            messages.error(request, 'Check your data')
    else:
        print(request.user)
        print(request.user.profile)
        userform = UserEditForm(instance=request.user)

    context = {'userform': userform}
    return render(request, 'accounts/edit_profile.html', context)


class UserListViewCBV(ListView):
    model = Profile
    template_name = "accounts/list_user.html"



class SocialPage(ListView):
    queryset = HomepageSection.objects.all()
    template_name = 'accounts/social_page.html'
    context_object_name = "list_section"


class UserList(LoginRequiredMixin, ListView):
    model = User
    template_name = 'accounts/users.html'


def user_profile_view(request, username):
    user = get_object_or_404(User, username=username)
    discussion_user = Discussion.objects.filter(author_discussion=user).order_by("-pk")
    context = {"user": user, "discussion_user": discussion_user}
    return render(request, 'accounts/user_profile_social.html', context)

exchangealgo/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h2 class="text-center">Edit Profile</h2>



	<form method="POST" action="{% url 'edit_profile' %}">
		{% csrf_token %}

		{% if form.errors %}
			<div class="alert alert-warning alert-dismissible" role="alert">
            <button class="close" data-dismiss="alert">
                    <small><sup>x</sup></small>
                </button>
            <p>Your Form Has Errors...</p>
            {% for field in form %}
            	{% if field.errors  %}
            		{{ field.errors }}
				{% endif %}


            {% endfor %}

          </div>
		{% endif %}


			 {{ userform|crispy }}
		     {{ profileform|crispy }}



		<input type="submit" value="Save Profile" class="btn-danger">
	</form>
    <br/>
    <p><small><a href="{% url 'password_change' %}">Click Here</a> To Change Your Password</small></p>

<br/><br/>
{% endblock %}

exchangealgo/accounts/templates/accounts/homepage.html
{% load static %}

<head>
    <title>Algorand Trading ALGO</title>
<body>
<table style="box-shadow:1px 1px 10px white">
    <div class="slideshow-container">
        <div class="mySlides fade">
            <img src="{% static 'img/algo.css' %}" style="width:1100px" height="350px">
        </div>
    </div>
            <br>
    <div style="text-align:center">
        <span class="dot"></span>
        <span class="dot"></span>
    </div>

    <tr style="background-color:blue;color:white;height:25px">
        <td><marquee behavior="alternate">
            Welcome now you can buy ALGO coin from Coinmarketcap or among users ...let's go!!
        </marquee></td>
    </tr>
</table>
</body>

exchangealgo/accounts/templates/accounts/list_user.html
{% extends 'base.html' %}

{% block head_title %}{{block.super}} -Users{% endblock head_title %}

{% block content %}

<h2 class="mt-3">Portfolio List Users</h2>
<hr>
{% for n in object_list %}
    {% if forloop.first %}<div class="row">{% endif %}
        <div class="col-lg-4">
            <div class="card my-1 border border-info">
                <div class="card-body py-0">
                    <p class="mb-0">
                        <a href="{% url 'user_profile' username=n.user.username %}">
                            <strong>@{{ n.user }}</strong>
                        </a>
                    </p>
                    Value PTF Algorand Coin = {{ n.ALGO_Wallet  }}COIN<br>
                    Value USD = {{ n.USD_wallet }}$<br>
                    profit = {{ n.profit }}
                </div>
            </div>
        </div>
    {% if forloop.counter|divisibleby:"3" or forloop.last %}</div>{% endif %}
    {% if forloop.counter|divisibleby:"3" and not forloop.last %}<div class="row">{% endif %}
{% endfor %}
</div>
{% endblock content %}

exchangealgo/accounts/templates/accounts/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}{{ block.super }} - Sign In{% endblock head_title %}

{% block content %}

    <div class="row justify-content-center mt-4">
        <div class="col-6 text-center">
            <h2>Sign Up!</h2>
            <form method="POST" novalidate>
               {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-info my-3" value="Create Account and Buy ALGORAND">
            </form>
        </div>
    </div>

{% endblock content %}

exchangealgo/accounts/templates/accounts/social_page.html
{% extends 'base.html' %}

{% block content %}

{% if request.user.is_staff %}
    <div class="card-body ps-0 pb-0">
        <a class="btn btn-sm btn-danger" href="{% url 'create_section' %}">Create Section</a>
    </div>
{% endif %}
 <div class="card my-5">
         <div class="card-header"style="background-color:blue;color:white;height:30px">
        <td><marquee behavior="alternate">
            Welcome now you can buy ALGO coin  ... CLICK ON ALGO CEX or ALGO DEX.....let's go !!
        </marquee></td>
    </div>
    </div>



<script>
    var slideIndex = 0;
    showSlides();

    function showSlides() {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        var dots = document.getElementsByClassName("dot");
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        slideIndex++;
        if (slideIndex > slides.length) {slideIndex = 1}
        for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
        }
        slides[slideIndex-1].style.display = "block";
        dots[slideIndex-1].className += " active";
        setTimeout(showSlides, 2000); // Change image every 2 seconds
    }
</script>
{% for section in list_section %}
    <div class="card my-3">
        <div class="card-header">
            <h5><a href="{{ section.get_absolute_url }}"><strong>{{ section.title_section }}</strong></a></h5>
            <p class="mb-0">{{ section.description }}</p>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-3">
                    <img src="{{ section.logo_section.url }}" style="max-width:100%">
                    <p>Total Discussion: {{ section.discussion_set.count }}
                    <br>Total Message: {{ section.get_number_of_posts_in_section }}</p>
                </div>
                <div class="col-lg-9">
                    <p>Last Discussion</p>
                    <table class="table table-hover">
                        <tbody>
                            {% for discussion in section.get_last_discussions.all %}
                                <tr class="row">
                                    <td class="col-lg-7 col-6">
                                        <a href="{% url 'discussion_view' pk=discussion.pk %}">{{ discussion.title }}</a>
                                    </td>
                                    <td class="col-lg-3 col-3">
                                        by <a href="#">{{ discussion.author_discussion }}</a>
                                    </td>
                                    <td class="col-lg-2 col-3">
                                        posts: {{ discussion.post_set.count }}</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>



{% endfor %}

{% endblock content %}

exchangealgo/accounts/templates/accounts/user_profile.html
{% extends 'base.html' %}

{% block head_title %}{{ block.super }} - {{ user }}{% endblock head_title %}
{% block content %}

<div class="row mt-5 prof">
    <div class="col-8">
        <div class="card my-3 ">
            <div class="card-header bg-info ">
                <h4>{% if request.user == user %}<h3><strong>{{ user}}</strong></h3>{% endif %}<strong>PORTFOLIO UPDATE</strong></h4>

                <div class="card-body ">
                <div class="card-header bg-primary"> date enter: {{ user.date_joined|date:"d M Y" }}
                <br>
                <p class="mb-0">- Total Algo in your Wallet = <strong>{{ algowallet }} ALGO</strong></p>
                    <p class="mb-0">- Total Ctv = <strong>{{ algo_usd }}$  </strong></p>
                <p class="mb-0">- Balance Wallet USD = <strong>{{ remaining_balance }}$</strong></p>
                <p class="mb-0">- Gain/Loss : <strong>{{ profit }}</strong></p>
                    <p class="mb-0">- PENDING USD: <strong>{{ pending_USD }}</strong></p>
                    <p class="mb-0">- PENDING ALGO: <strong>{{ pending_ALGO }}</strong></p>
                </div>
                </div>
            </div>
        </div>
    </div>
 </div>
<div class="col-4">
    <div class="card my-3 ">
        <div class="card-header bg-info">
            <h4>General Market Current</h4>
        </div>
        <div class="card-body">
            <div class="card-body">
                <p>ALGO/USD: <strong>{{ price }}$</strong></p>
                <p>Market cap: <strong>{{ market_cap }}%</strong></p>
                <p>Volume 24h: <strong>{{ vol24h }}%</strong></p>
                <p>Percentage change 24h: <strong>{{ percent_24h }}%</strong></p>
            </div>
        </div>
        <div class="card-footer bg-primary"></div>
        </div>
        </div>
        <div class="row mt-3">
            <div class="col-sm-4"></div>
                <div class="card my-3">
                    <div class="card-header bg-info">
                        <h4>Status Order </h4>
                    </div>
                        <div class="card-body">
                            <div class="card-body">
                                <p>{% if request.user == user %}<h3><strong>Your Status Order</strong></h3> {% endif %}</p>
                                <hr>
                                    {% for ordering in orders %}
                                <strong><h4><br>Number Order {{ ordering.order_number }}</h4>Status-><strong>({{ ordering.status }})  </strong>{{ ordering.datetime}}</strong>
                                    {% endfor %}
                            </div>
                        </div>
                 <div class="card-footer bg-primary"></div>
            </div>
        </div>
     </div>
</div>

    <div class="card my-0">
        <div class="card-header bg-info">
            <h4><strong>Latest Public Transaction</strong></h4> <h6>- soon as the transaction is concluded, you will have the opportunity to view the bookorde-</h6>
        </div>
            <div class="card-body">
                {% for order_transaction in orders_transactions %}
                     <div class="lead"> Date Transaction: {{ order_transaction.datetime|date:"M d Y H:m:s"  }}
                    <hr>
                <br></div>
                    <p>{% if order_transaction.call == request.user %}Type : Call from {{ order_transaction.put }}{% endif %}</p>
                    <p>{% if order_transaction.put == request.user  %}Type : Sell to {{ order_transaction.call }}{% endif %}</p>
                    <p class="mb-0">Quantity: {{ order_transaction.quantity }} - Price: {{ order_transaction.price }}</p>
                        {% endfor %}
            </div>
        <div class="card-footer bg-primary"></div>
    </div>
 </div>
{% endblock content %}

exchangealgo/accounts/templates/accounts/user_profile_social.html
{% extends 'base.html' %}

{% block head_title %}{{ block.super }} - {{ user }}{% endblock head_title %}

{% block content %}
<div class="row mt-3">
    <div class="col-4">
        <div class="card my-2">
            <div class="card-header bg-info">
                <h4>{% if request.user == user %}Il Tuo {% endif %}User Profile</h4>
            </div>
            <div class="card-body">
                <p class="lead">@{{ user }}</p>
                <p class="mb-0">Registration: {{ user.date_joined|date:"d M Y" }}</p>
                <p class="mb-0">Discussion: {{ user.discussion.count }}</p>
                <p class="mb-0">Posts: {{ user.posts.count }}</p>
            </div>
            <div class="card-footer bg-primary"></div>
        </div>
    </div>

    <div class="col-8">
        <div class="card my-2">
            <div class="card-header bg-info">
                <h4>Discussion Done</h4>
            </div>
            <div class="card-body">
                {% for discussion in discussion_user %}
                    <a href="{{ discussion.get_absolute_url }}">{{ discussion.title }}</a>
                    <p class="text-muted">{{ discussion.membership }} {{ discussion.published }}</p>
                {% empty %}
                    {% if request.user != user %}
                        <p>{{ user }} You have not created any threads! !</p>
                    {% else %}
                        <p>You have not created any threads! Start now!</p>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="card-footer bg-primary"></div>
        </div>
    </div>
</div>
{% endblock content %}

exchangealgo/accounts/templates/accounts/users.html
{% extends 'base.html' %}

{% block head_title %}{{ block.super }} - Users List Social{% endblock head_title %}

{% block content %}

<h2 class="mt-3">Users List Social</h2>
<hr>
{% for user in object_list %}
    {% if forloop.first %}<div class="row">{% endif %}
        <div class="col-lg-4">
            <div class="card my-1 border border-info">
                <div class="card-body py-0">
                    <p class="mb-0">
                        <a href="{% url 'user_profile_social' username=user.username %}"><strong>@{{ user.username }}</strong>
                        </a>
                    </p>
                    Registration: {{ user.date_joined|date:"d M Y" }}<br>
                    Posts: {{ user.posts.count }}<br>
                    Discussions: {{ user.discussions.count }}
                </div>
            </div>
        </div>
    {% if forloop.counter|divisibleby:"3" or forloop.last %}</div>{% endif %}
    {% if forloop.counter|divisibleby:"3" and not forloop.last %}<div class="row">{% endif %}
{% endfor %}
</div>
{% endblock content %}